services:
  postgresql:
    type: postgresql:16
    configuration:
      extensions:
        - vector

applications:
  ollama:
    stack:
      - "python@3.12"
      - "ollama"
    container_profile: BALANCED
    relationships:
      db: "postgresql:postgresql"
    mounts:
      "/.ollama":
        source: "storage"
        source_path: ".ollama"
    web:
      commands:
        start: "OLLAMA_HOST=:$PORT ollama serve"
    hooks:
      build: |
        set -eux
        cd vectorize/
        pip install -r requirements.txt
      deploy: |
        set -eux
        set -a
        . /app/.env
        export OLLAMA_HOST=:$PORT
        ollama pull $EMBEDDING_MODEL
        ollama pull $CHAT_MODEL

        cd vectorize/
        python vectorize.py

  app:
    stack:
      - "nodejs@22"
    relationships:
      db: "postgresql:postgresql"
      ollama: "ollama:http"
    mounts:
      "/.npm":
        source: "storage"
        source_path: "npm"
    web:
      commands:
        start: "npx next start -p $PORT"
    hooks:
      build: |
        set -eux
        npm install
        npx prisma generate
        npm run build

routes:
  "https://{default}/":
    type: upstream
    upstream: "app:http"
